# Generated by Django 4.0.6 on 2022-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='media/post'),
        ),
    ]
