# Generated by Django 4.0.6 on 2022-09-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_image_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image_post',
            new_name='imagepost',
        ),
    ]
