# Generated by Django 4.0.6 on 2022-09-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_image_post_blog_imagepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_messenger', models.CharField(max_length=60)),
                ('image_messenger', models.ImageField(upload_to='media')),
            ],
        ),
    ]
