# Generated by Django 4.0.6 on 2022-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagepost',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
