# Generated by Django 4.0.6 on 2022-09-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_imagepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagepost',
        ),
    ]
