# Generated by Django 4.0.6 on 2022-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blog_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
