# Generated by Django 4.0.6 on 2022-09-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_messenger_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messenger',
            name='image_post',
        ),
        migrations.AddField(
            model_name='messenger',
            name='imagepost',
            field=models.ImageField(blank=True, null=True, upload_to='media/post'),
        ),
    ]
