# Generated by Django 4.0.6 on 2022-10-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_remove_messenger_image_post_messenger_imagepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='messenger',
            name='imagepost',
        ),
    ]
